ALTER TABLE public.configuracion
  ADD COLUMN IF NOT EXISTS banco_nombre  TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS banco_titular TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS banco_numero  TEXT NOT NULL DEFAULT '';
